print('Hello')
print('What is your name')
name=input()
print('Your name is'+name)
print('Length of your name is')
print(len(name))
print('What is your age')
age=input()
print('Your age in year will be'+str(int(age)+1))
